import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats as sp

###########################################################################################################

def get_data(start: str = "2000-01-01", end: str = "2026-03-31") -> pd.DataFrame:
    """
    Download stock data, clean it and return a DataFrame of daily losses.

    Parameters
    ----------

    start : str
        Start date in format 'YYYY-MM-DD'.
    end : str
        End date in format 'YYYY-MM-DD'.

    Returns
    -------
    loss_df : pd.DataFrame
        DataFrame containing daily log-losses for each stock.
    """
    
    if not isinstance(start, str) or not isinstance(end, str):
        raise TypeError("start and end must be strings in format 'YYYY-MM-DD'")

    
    data = {
        "Kinnevik B": yf.download("KINV-B.ST", start=start, end=end, interval="1d", auto_adjust=True, progress=False),
        "Investor B": yf.download("INVE-B.ST", start=start, end=end, interval="1d", auto_adjust=True, progress=False),
        "SEB A": yf.download("SEB-A.ST", start=start, end=end, interval="1d", auto_adjust=True, progress=False),
        "Nordea Bank": yf.download("NDA-SE.ST", start=start, end=end, interval="1d", auto_adjust=True, progress=False),
        "Castellum": yf.download("CAST.ST", start=start, end=end, interval="1d", auto_adjust=True, progress=False),
        "Skanska B": yf.download("SKA-B.ST", start=start, end=end, interval="1d", auto_adjust=True, progress=False),
        "ABB": yf.download("ABB.ST", start=start, end=end, interval="1d", auto_adjust=True, progress=False),
        "Atlas Copco A": yf.download("ATCO-A.ST", start=start, end=end, interval="1d", auto_adjust=True, progress=False),
        "Boliden": yf.download("BOL.ST", start=start, end=end, interval="1d", auto_adjust=True, progress=False),
        "SCA B": yf.download("SCA-B.ST", start=start, end=end, interval="1d", auto_adjust=True, progress=False)
    }

    data_clean = {}
    for k, df in data.items():
        data_clean[k] =  df.copy().dropna() 

    for df in data_clean.values():
        df["lgr"] = np.log(df["Close"]).diff()

    loss_df = pd.DataFrame()
    for k in data_clean.keys():
        loss_df[k] = -data_clean[k]["lgr"]

    loss_df.dropna(inplace=True)  
   
    return loss_df


def createPortfolio(shares, weights: np.ndarray):
    """
    Create a portfolio from shares and weights.

    Parameters
    ----------
    shares : iterable
        Iterable of return/loss series.
    weights : np.ndarray
        Array of portfolio weights.

    Returns
    -------
    portfolio : pd.Series
        Weighted portfolio series.
    """
    portfolio = sum(share * weight for share, weight in zip(shares, weights))
    return pd.DataFrame(portfolio, columns=["Portfolio"])



def get_extreme_data(thresholds: list, data: pd.DataFrame, exceedances: bool = False) -> tuple[dict[str, float], pd.DataFrame]:
    """
    Filter the dataset with given thresholds using POT.

    Parameters
    ----------
    thresholds : list
        Threshold values, one per column in data.
    data : pd.DataFrame
        DataFrame generated by get_data().
    exceedances : bool
        If True, return exceedances x - u for x > u.
        If False, return the observations x for x > u.

    Returns
    -------
    u : dict
        Dictionary mapping stock names to threshold values.
    extreme_data : pd.DataFrame
        DataFrame containing threshold exceedances or extreme observations.
    """
    if not isinstance(thresholds, list):
        raise TypeError("thresholds must be a list")
    elif not isinstance(data, pd.DataFrame):
        raise TypeError("data must be a DataFrame")
    elif not isinstance(exceedances, bool):
        raise TypeError("exceedances must be a bool")

    if len(thresholds) != len(data.columns):
        raise ValueError("Number of thresholds must match number of columns in data")

    u = dict(zip(data.columns, thresholds))
    extreme_data = data.copy()

    for k in extreme_data.columns:
        if exceedances:
            extreme_data[k] = (extreme_data.loc[extreme_data[k] > u[k], k] - u[k]).astype(float)
        else:
            extreme_data[k] = extreme_data.loc[extreme_data[k] > u[k], k].astype(float)

    return u, extreme_data



def get_cluster_maxima(thresholds: dict[str, float], data: pd.DataFrame, r: int) -> tuple[dict[str, pd.DataFrame], dict[str, pd.DataFrame]]:
    """
    Identify exceedance clusters using r-runs-declustering and return
    the maximum exceedance from each cluster.

    Parameters
    ----------
    thresholds : dict[str, float]
        Threshold values by stock.
    data : pd.DataFrame
        DataFrame of losses.
    r : int
        Maximum gap in calendar days before a new cluster starts.

    Returns
    -------
    cluster_maxima : dict[str, pd.DataFrame]
        Dictionary mapping each stock to a DataFrame containing the
        maximum exceedance from each cluster.

    clustered_exceedances : dict[str, pd.DataFrame]
        Dictionary mapping each stock to a DataFrame containing all
        exceedances together with their assigned cluster.

    """
    if not isinstance(thresholds, dict):
        raise TypeError("thresholds must be a dictionary")
    elif not isinstance(data, pd.DataFrame):
        raise TypeError("data must be a DataFrame")
    elif not isinstance(r, int):
        raise TypeError("r must be an int")

    cluster_maxima = {}
    clustered_exceedances = {}

    for k in data.columns:
        series = data[k]
        threshold = thresholds[k]
        exceedances = series[series > threshold]

        if exceedances.empty:
            cluster_maxima[k] = pd.DataFrame(columns=["Loss", "Cluster"])
            continue

        dates = exceedances.index
        values = exceedances.values

        cluster_id = np.zeros(len(exceedances), dtype=int)
        current_cluster = 0
        max_gap = pd.Timedelta(days=r)

        for i in range(1, len(exceedances)):
            if dates[i] - dates[i - 1] > max_gap:
                current_cluster += 1
            cluster_id[i] = current_cluster

        declustered_df = pd.DataFrame({"Loss": values, "Cluster": cluster_id}, index=dates)

        clustered_exceedances[k] = declustered_df
        idx = declustered_df.groupby("Cluster")["Loss"].idxmax()
        cluster_maxima[k] = declustered_df.loc[idx]

    return cluster_maxima, clustered_exceedances

###########################################################################################################

def staticFiltering(thresholds: dict[str, float], data: pd.DataFrame, window_size: int) -> dict:
    """
    Construct non-overlapping recovery windows after extreme losses.

    Parameters
    ----------
    thresholds : dict[str, float]
        Threshold values by stock.
    data : pd.DataFrame
        DataFrame generated by get_data().
    window_size : int
        Length of each recovery window in calendar days.

    Returns
    -------
    recovery_windows : dict
        Dictionary mapping stock name to a DataFrame with columns
        "start" and "end" for each recovery window.
    """
    if not isinstance(thresholds, dict):
        raise TypeError("thresholds must be a dictionary")
    elif not isinstance(data, pd.DataFrame):
        raise TypeError("data must be a DataFrame")
    elif not isinstance(window_size, int):
        raise TypeError("s must be an int")

    recovery_windows = {}

    for k in data.columns:
        series = data[k]
        threshold = thresholds[k]
        exceed_mask = series > threshold
        exceedances = series[exceed_mask]

        dates = exceedances.index
        window_length = pd.Timedelta(days=window_size)

        if len(dates) == 0:
            recovery_windows[k] = pd.DataFrame(columns=["start", "end"])
            continue

        pivot = dates[0]
        start = [pivot]
        end = [pivot + window_length]

        for i in range(1, len(dates)):
            if dates[i] - pivot > window_length:
                pivot = dates[i]
                start.append(pivot)
                end.append(pivot + window_length)

        recovery_windows[k] = pd.DataFrame({
            "start": start,
            "end": end
        })

    return recovery_windows


def Generate_Recovery_Data(data: pd.DataFrame, event_periods: dict[str, pd.DataFrame], stock: str, window_size: int = 10):
    """
    Generate recovery data after extreme losses.

    Parameters
    ----------
    data : pd.DataFrame
        DataFrame generated by get_data().
    event_periods : dict[str, pd.DataFrame]
        Dictionary mapping each stock to a DataFrame with columns
        "start" and "end". This can represent the recovery windows
        from staticFiltering().
    stock : str
        Stock name.
    window_size : int
        Fixed recovery horizon in days when dynamic=False.


    Returns
    -------
    recoveries : pd.DataFrame
        DataFrame containing loss and recovery values.
    partial_recovery : pd.DataFrame
        Events with partial recovery.
    full_recovery : pd.DataFrame
        Events with full recovery.
    no_recovery : pd.DataFrame
        Events with no recovery.
    recovery_ratio : float
        Fraction of full recoveries among all events.
    """
    if not isinstance(data, pd.DataFrame):
        raise TypeError("data must be a DataFrame")
    elif not isinstance(event_periods, dict):
        raise TypeError("event_periods must be a dictionary")
    elif not isinstance(stock, str):
        raise TypeError("stock must be a string")
    elif not isinstance(window_size, int):
        raise TypeError("window_size must be an int")

    if stock not in event_periods:
        raise KeyError(f"{stock} not found in event_periods")

    recovery_period = pd.Timedelta(window_size, "D")
    plus_one = pd.Timedelta("1D")
    starts = event_periods[stock]["start"]

    vals = [data[stock].loc[d + plus_one : d + plus_one + recovery_period].sum() for d in starts]
   
    recoveries = pd.DataFrame({f"{window_size} day recovery": vals, "Loss": data[stock].loc[starts].values}, index=starts)
    
    recovery_col = f"{window_size} day recovery"
    recovery_amount = -recoveries[recovery_col]
    loss = recoveries["Loss"]
    
    recovery_50plus = recoveries[(recovery_amount >= loss/2) & (recovery_amount<loss)]
    recovery_50minus = recoveries[(recovery_amount >= 0) & (recovery_amount<loss/2)]
    full_recovery = recoveries[recovery_amount >= loss]
    no_recovery = recoveries[recovery_amount < 0]

    n = len(starts)
    zero_ratio = len(no_recovery) / n
    ratio_50minus= len(recovery_50minus) / n
    ratio_50plus= len(recovery_50plus) / n 
    full_ratio = len(full_recovery) / n

    ratios = np.array([zero_ratio, ratio_50minus, ratio_50plus, full_ratio])

    return ratios, recoveries,  no_recovery, recovery_50minus, recovery_50plus, full_recovery

###########################################################################################################

# GPD-POT: Maximum-likelihood-estimation, return-levels and standard error via delta-method


# Negative log-likelihood for the GPD
def gpd_negloglik(params, excesses):
    sigma, xi = params
    y = np.asarray(excesses, dtype=float)
    k = len(y)

    if sigma <= 0:
        return np.inf

    if abs(xi) < 1e-6:
        return k * np.log(sigma) + np.sum(y) / sigma

    z = 1 + xi * y / sigma
    if np.any(z <= 0):
        return np.inf
    return k * np.log(sigma) + (1 + 1 / xi) * np.sum(np.log(z))

# Numerical Hessian via central finite differences
def numerical_hessian(func, params, excesses, h=1e-4):
    params = np.asarray(params, dtype=float)
    n = len(params)
    H = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            ei = np.zeros(n)
            ej = np.zeros(n)
            ei[i] = h
            ej[j] = h

            fpp = func(params + ei + ej, excesses)
            fpm = func(params + ei - ej, excesses)
            fmp = func(params - ei + ej, excesses)
            fmm = func(params - ei - ej, excesses)

            H[i, j] = (fpp - fpm - fmp + fmm) / (4 * h * h)
    return H

# Covariance matrix from the observed GPD information matrix
def gpd_cov_matrix(excesses, sigma_hat, xi_hat, h=1e-4):
    H = numerical_hessian(gpd_negloglik, np.array([sigma_hat, xi_hat]), excesses, h=h)
    return np.linalg.inv(H)

# Estimated GPD return level
def return_level_hat(u, sigma_hat, xi_hat, rate, m):
    if abs(xi_hat) > 1e-6:
        return u + (sigma_hat / xi_hat) * ((m * rate) ** xi_hat - 1)
    else:
        return u + sigma_hat * np.log(m * rate)

# Delta-method standard error for the GPD return level
def return_level_se(u, sigma_hat, xi_hat, rate, n_total, cov_mat, m):
    mr = m * rate
    var_rate = rate * (1 - rate) / n_total

    if abs(xi_hat) > 1e-6:
        d_rate = sigma_hat * m * (mr ** (xi_hat - 1))
        d_sigma = ((mr ** xi_hat) - 1) / xi_hat
        d_xi = -(sigma_hat / xi_hat**2) * ((mr ** xi_hat) - 1) + (sigma_hat / xi_hat) * (mr ** xi_hat) * np.log(mr)
    else:
        d_rate = sigma_hat / rate
        d_sigma = np.log(mr)
        d_xi = 0.5 * sigma_hat * (np.log(mr) ** 2)

    grad = np.array([d_rate, d_sigma, d_xi])

    V = np.array([
        [var_rate, 0.0, 0.0],
        [0.0, cov_mat[0, 0], cov_mat[0, 1]],
        [0.0, cov_mat[1, 0], cov_mat[1, 1]]
    ])

    var_xm = grad @ V @ grad
    return np.sqrt(var_xm)





